### ISSUE TITLE
how to use ?

### ISSUE THREAD

**Issue by ctf0** [t32k/material-design-color-palette#1]
thanx for this time saver but i have one problem ,i there something i should do b4 hand for this plugin to work ?
i mean i open sketch ,do the same as in the demo ss but all i get is a couple of folders with an empty shape :(

**Comment by t32k** [comment]
@ctf0 
Please re-install it from Sketch Toolbox.app.
If you can't do that again, please let me know your environment info(eg. Mac OS Ver. Sketch.app Ver. that plugin Ver(See also: sketchpack.json). and Screen Captures).

**Comment by ctf0** [comment]
@t32k 
![ss](https://cloud.githubusercontent.com/assets/7388088/5658333/efad0e60-9708-11e4-8753-37dd3b96ae08.jpg)

OSX 10.9.5
Sketch 3.1
Sketch Toolbox (the latest from its webpage)
Plugin 2.1.0

**Comment by t32k** [comment]
Hum... I have no idea.
Perhaps, it might be because of Sketch 3.1. I use Sketch v3.2 and OSX 10.10 but it goes well. Unfortunately, I don't have Sketch 3.1. so, please try Sketch Beta v3.2.2. You can use it with OS X 10.9.
http://bohemiancoding.com/sketch/beta/

**Comment by ctf0** [comment]
now it works ,i thought any plugin that work on the base version should work on any future sub versions as-well ,still many thanx for ur help :+1: .
