### ISSUE TITLE
color name/value on swatch

### ISSUE THREAD

**Issue by marco-piccolino** [t32k/material-design-color-palette#2]
Hi! congrats, darn useful plugin...

it would be very useful to have the color name and value on the swatch besides the HEX, to implement a design on material implementations that support the name-value scheme

**Comment by t32k** [comment]
@marco-piccolino 

I don't want those labels, because It's obvious.
However, if you really want it, please pull request.
I would merge it.

**Comment by marco-piccolino** [comment]
Ok, thanks. I'll try and get it in. I really do see a use case for that.
