### ISSUE TITLE
Sketch v3.8.1 Breaks this plugin.

### ISSUE THREAD

**Issue by JWhiteUX** [t32k/material-design-color-palette#6]
This plugin only generates the RED color palette when selecting "All Colors."

**Comment by cooliean** [comment]
Sketch v3.8.3 is not work too.

**Comment by t32k** [comment]
@JWhiteUX @cooliean 

Please install the plugin v3.1.0  🙇 
- [Release Material Design Color Palette v3.1.0](https://github.com/t32k/material-design-color-palette/releases/tag/v3.1.0)
