### ISSUE TITLE
目前插件在 SKETCH 39  不能使用

### ISSUE THREAD

**Issue by RETHINKAIZ** [t32k/material-design-color-palette#8]
hi,t32K
目前插件在SKETCH39 中插件点击后么有任何反应。是不是不支持 SKETCH 39版本

**Comment by t32k** [comment]
I know what you want to say. 
OK, I'll fix it.

**Comment by tjementum** [comment]
I assume the title says "Material Design Color Palette" plugin does not work in the latest version 39 of Sketch? Any status?

**Comment by markhuang1212** [comment]
"Can't use in Sketch 39". It is what it says, and I have this situation as well.

**Comment by andrewnenakhov** [comment]
I can't use it in Sketch 40.3 too.

**Comment by Solliu** [comment]
fix it plz...

**Comment by t32k** [comment]
Thanks to @littlebusters, this issue was solved. #9 

Please download and install __v4.0.0__.
https://github.com/t32k/material-design-color-palette/releases/tag/v4.0.0
